openapi: 3.0.3
info:
  title: PM Companies API
  version: 1.0.0
  description: API for managing companies with hierarchical organization, import/export, and configuration endpoints.

servers:
  - url: http://localhost:5000

paths:
  /companies:
    get:
      tags:
        - Companies
      description: Retrieve a list of companies
      summary: List all companies
      responses:
        '200':
          description: List of companies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
    post:
      tags:
        - Companies
      description: Create a new company
      summary: Create a new company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyInput'
      responses:
        '201':
          description: Company created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '400':
          description: Validation error

  /companies/{company_id}:
    get:
      tags:
        - Companies
      description: Retrieve a company by ID
      summary: Get a company by ID
      parameters:
        - in: path
          name: company_id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Company found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '404':
          description: Company not found
    put:
      tags:
        - Companies
      description: Update a company by ID
      summary: Update a company by ID
      parameters:
        - in: path
          name: company_id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyInput'
      responses:
        '200':
          description: Company updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '400':
          description: Validation error
        '404':
          description: Company not found
    patch:
      tags:
        - Companies
      description: Partially update a company by ID
      summary: Partially update a company by ID
      parameters:
        - in: path
          name: company_id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyInput'
      responses:
        '200':
          description: Company updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '400':
          description: Validation error
        '404':
          description: Company not found
    delete:
      tags:
        - Companies
      description: Delete a company by ID
      summary: Delete a company by ID
      parameters:
        - in: path
          name: company_id
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Company deleted
        '404':
          description: Company not found

  /export/csv:
    get:
      tags:
        - Export
      description: Export all companies as CSV
      summary: Export all companies as CSV
      responses:
        '200':
          description: CSV file with all companies
          content:
            text/csv:
              schema:
                type: string
                format: binary

  /import/csv:
    post:
      tags:
        - Import
      description: Import companies from a CSV file
      summary: Import companies from a CSV file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Import successful
        '207':
          description: Partial import with errors
        '400':
          description: Import failed

  /import/json:
    post:
      tags:
        - Import
      description: Import companies from a JSON file
      summary: Import companies from a JSON file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Import successful
        '207':
          description: Partial import with errors
        '400':
          description: Import failed

  /version:
    get:
      tags:
        - Meta
      description: Get API version
      summary: Get API version
      responses:
        '200':
          description: API version
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string

  /config:
    get:
      tags:
        - Meta
      description: Get application configuration
      summary: Get application configuration
      responses:
        '200':
          description: Application configuration
          content:
            application/json:
              schema:
                type: object
                properties:
                  FLASK_ENV:
                    type: string
                  DEBUG:
                    type: string
                  DATABASE_URI:
                    type: string

components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        logo_url:
          type: string
        parent_id:
          type: string
          nullable: true
        organization_id:
          type: string
          nullable: true
        address:
          type: string
        email:
          type: string
        phone_number:
          type: string
        website:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        is_active:
          type: boolean
        registration_number:
          type: string
        tax_id:
          type: string
        country:
          type: string
        city:
          type: string
        postal_code:
          type: string
        employees_count:
          type: integer
    CompanyInput:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        logo_url:
          type: string
        parent_id:
          type: string
        organization_id:
          type: string
        address:
          type: string
        email:
          type: string
        phone_number:
          type: string
        website:
          type: string
        registration_number:
          type: string
        tax_id:
          type: string
        country:
          type: string
        city:
          type: string
        postal_code:
          type: string
        employees_count:
          type: integer
        is_active:
          type: boolean